version: '3.8'

services:
  resume-matcher:
    build: .
    container_name: resume-matcher
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
    restart: unless-stopped

networks:
  default:
    name: resume-matcher-network
